export const SEED_USERS = [
  {
    name: "Ayesha Khan",
    email: "ayesha@helplytics.ai",
    role: "Both",
    location: "Karachi",
    skills: ["Figma", "UI/UX", "HTML/CSS", "Career Guidance"],
    needsHelpWith: ["React", "Node.js"],
    interests: ["Hackathons", "UI/UX", "Community Building"],
    trustScore: 100,
    helpCount: 35,
    badgesEarned: ["Design Ally", "Fast Responder", "Top Mentor"],
    requestsCreated: 2,
    photoURL: "",
    createdAt: new Date().toISOString(),
  },
  {
    name: "Hassan Ali",
    email: "hassan@helplytics.ai",
    role: "Can Help",
    location: "Lahore",
    skills: ["JavaScript", "React", "Git/GitHub"],
    needsHelpWith: ["Machine Learning", "Data Science"],
    interests: ["Open Source", "Backend Dev"],
    trustScore: 88,
    helpCount: 24,
    badgesEarned: ["Code Rescuer", "Fast Responder"],
    requestsCreated: 0,
    photoURL: "",
    createdAt: new Date().toISOString(),
  },
  {
    name: "Sara Noor",
    email: "sara@helplytics.ai",
    role: "Both",
    location: "Islamabad",
    skills: ["Python", "Data Analysis", "Research"],
    needsHelpWith: ["Frontend", "Design"],
    interests: ["Data Science", "Community Voice"],
    trustScore: 74,
    helpCount: 11,
    badgesEarned: ["Community Voice"],
    requestsCreated: 2,
    photoURL: "",
    createdAt: new Date().toISOString(),
  },
];

export const SEED_REQUESTS = [
  {
    title: "Need help making my portfolio responsive before demo day",
    description: "My HTML/CSS portfolio breaks on tablets and I need layout guidance before tomorrow evening. The grid collapses and nav items overflow on smaller screens.",
    category: "Web Development",
    urgency: "High",
    status: "Solved",
    tags: ["HTML/CSS", "Responsive", "Portfolio"],
    aiSummary: "Responsive layout issue with a short deadline. Best helpers are frontend mentors comfortable with CSS grids and media queries.",
    userName: "Sara Noor",
    userLocation: "Karachi",
    helpers: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    title: "Looking for Figma feedback on a volunteer event poster",
    description: "I have a draft poster for a campus community event and want sharper hierarchy, spacing, and CTA copy. The current version feels cluttered.",
    category: "Design",
    urgency: "Medium",
    status: "Open",
    tags: ["Figma", "Poster", "Design Review"],
    aiSummary: "A visual design critique request where feedback on hierarchy, spacing, and messaging would create the most value.",
    userName: "Ayesha Khan",
    userLocation: "Lahore",
    helpers: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    title: "Need mock interview support for internship applications",
    description: "Applying to frontend internships and need someone to practice behavioral and technical interview questions with me. I want to cover React fundamentals and system design basics.",
    category: "Career",
    urgency: "Low",
    status: "Solved",
    tags: ["Interview Prep", "Career", "Frontend"],
    aiSummary: "Career coaching request focused on confidence-building, behavioral answers, and entry-level frontend interviews.",
    userName: "Sara Noor",
    userLocation: "Remote",
    helpers: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    title: "Need help with JavaScript async/await and Promises",
    description: "I understand callbacks but I am confused about how async/await compares to Promises. Need a 30-minute session to walk me through practical examples.",
    category: "Web Development",
    urgency: "High",
    status: "Open",
    tags: ["JavaScript", "Async", "Promises"],
    aiSummary: "JavaScript fundamentals request focused on async patterns. Best suited for mid-level JavaScript developers.",
    userName: "Ayesha Khan",
    userLocation: "Karachi",
    helpers: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    title: "Need review on my machine learning model accuracy",
    description: "I built a classification model using scikit-learn and getting 68% accuracy on validation. Looking for guidance on feature selection and model tuning strategies.",
    category: "Data Science",
    urgency: "Medium",
    status: "Open",
    tags: ["Python", "Machine Learning", "scikit-learn"],
    aiSummary: "Data science request focused on ML model performance. Best suited for experienced ML practitioners.",
    userName: "Sara Noor",
    userLocation: "Islamabad",
    helpers: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
];

export const SEED_MESSAGES = [
  {
    senderName: "Ayesha Khan",
    receiverName: "Sara Noor",
    lastMessage: "I checked your portfolio request. Share the breakpoint screenshots and I can suggest fixes.",
    lastTimestamp: "09:45 AM",
    participants: [],
    createdAt: new Date().toISOString(),
  },
  {
    senderName: "Hassan Ali",
    receiverName: "Ayesha Khan",
    lastMessage: "Your event poster concept is solid. I would tighten the CTA and reduce the background texture.",
    lastTimestamp: "11:10 AM",
    participants: [],
    createdAt: new Date().toISOString(),
  },
];

export const SEED_NOTIFICATIONS = [
  { type: "Status", text: '"Need help making my portfolio responsive before demo day" was marked as solved', read: false, createdAt: new Date().toISOString() },
  { type: "Match", text: 'Ayesha Khan offered help on "JavaScript async/await" request', read: false, createdAt: new Date().toISOString() },
  { type: "Request", text: 'Your request "Need help with JavaScript async/await" is now live in the community feed', read: false, createdAt: new Date().toISOString() },
  { type: "Match", text: "New helper matched to your responsive portfolio request", read: false, createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString() },
  { type: "Reputation", text: "Your trust score increased after a solved request", read: false, createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString() },
  { type: "Insight", text: "AI Center detected rising demand for interview prep", read: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
];
